import type { CSSProperties } from 'react';

export const chatStyles: { [key: string]: CSSProperties } = {
  container: {
    fontFamily: 'Arial, sans-serif',
    height: '100vh',
    display: 'flex',
    flexDirection: 'column',
    margin: '0 20px',
    backgroundColor: '#fff',
    boxSizing: 'border-box',
  },
  header: {
    padding: '20px',
    borderBottom: '1px solid #eee',
    backgroundColor: '#f8f9fa',
  },
  heading: {
    textAlign: 'center',
    color: '#333',
    margin: '0',
    fontSize: '24px',
  },
  chatArea: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  messagesContainer: {
    flex: 1,
    padding: '20px',
    overflowY: 'auto',
    backgroundColor: '#f5f5f5',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  messageBubble: {
    maxWidth: '70%',
    padding: '12px 16px',
    borderRadius: '18px',
    wordBreak: 'break-word',
    fontSize: '14px',
    lineHeight: '1.4',
    margin: 0,
  },
  userMessage: {
    backgroundColor: '#007bff',
    color: 'white',
    alignSelf: 'flex-end',
    borderBottomRightRadius: '4px',
  },
  aiMessage: {
    backgroundColor: 'white',
    color: '#333',
    alignSelf: 'flex-start',
    borderBottomLeftRadius: '4px',
    border: '1px solid #e0e0e0',
  },
  messageText: {
    whiteSpace: 'pre-wrap',
    margin: 0,
  },
  inputArea: {
    padding: '20px',
    borderTop: '1px solid #eee',
    backgroundColor: '#fff',
    position: 'sticky',
    bottom: 0,
    boxSizing: 'border-box',
    flexShrink: 0,
  },
  inputContainer: {
    display: 'flex',
    gap: '10px',
    alignItems: 'flex-end',
  },
  textarea: {
    flex: 1,
    padding: '12px',
    border: '1px solid #ccc',
    borderRadius: '8px',
    fontSize: '16px',
    resize: 'none',
    minHeight: '60px',
    maxHeight: '120px',
    fontFamily: 'inherit',
  },
  buttonContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  button: {
    padding: '12px 20px',
    backgroundColor: '#007bff',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontSize: '16px',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease',
    minWidth: '100px',
  },
  clearButton: {
    padding: '12px 20px',
    backgroundColor: '#6c757d',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontSize: '16px',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease',
    minWidth: '100px',
  },
  errorText: {
    color: 'red',
    marginTop: '10px',
    textAlign: 'center',
    padding: '10px',
    backgroundColor: '#ffe0e0',
    borderRadius: '4px',
  },
  welcomeMessage: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: '#666',
    fontSize: '16px',
    textAlign: 'center',
  },
  typingIndicator: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    color: '#666',
    fontSize: '14px',
    fontStyle: 'italic',
  }
};
